### ISSUE TITLE
Document installing dependencies & building Storybook

### ISSUE THREAD

**Issue by kylesuss** [chromaui/action#16]
I received a support request from someone who was getting the error:

> Could not discover Storybook version. Try upgrading the chromatic-cli package?

Turns out the steps to fix were to add the `run` commands to the yml config file for them to install dependencies & build their Storybook. I believe the docs should call this out somewhere so it is obvious that you have to fill in that information for your specific setup. As I read the docs now, I get the impression that the config we provide is the only thing you need to get the action working.

**Comment by ndelangen** [comment]
https://github.com/chromaui/action/commit/d8dc724d2f1aab38295a73419c812f253f060e66
