### ISSUE TITLE
Error messages are not printed to the console

### ISSUE THREAD

**Issue by alexjfno1** [chromaui/action#32]
When running storybook in GitHub Actions the error messages are not always printed to the console. 

In Storybook I have defined a viewport size above the allowed value. When running locally the cli produces the error:

```
✖ Failed to verify your Storybook
Viewport 1920 out of range [320, 1800]
```

However when I run in GitHub Actions the job fails but gives no indication of what failed:

![image](https://user-images.githubusercontent.com/2777141/87293189-de146200-c4f9-11ea-9d93-a574e60863ba.png)

**Comment by ghengeveld** [comment]
Thanks for reporting. We have a new CLI with better error reporting, but our GitHub Action is still using the old one. We'll release a new version of the action sometime this week to update the CLI. That should improve your error logging.

**Comment by ndelangen** [comment]
Let's do it tomorrow @ghengeveld ?
