### ISSUE TITLE
Monorepos: "Could not find a supported Storybook viewlayer package"

### ISSUE THREAD

**Issue by daniel-ac-martin** [chromaui/action#35]
I've run up against the following error:
```
Error: ✖ Failed to collect Storybook metadata
Could not find a supported Storybook viewlayer package. Make sure one is installed.
  at /home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/lib/getStorybookInfo.js:86:11
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async getStorybookInfo (/home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/lib/getStorybookInfo.js:116:25)
  at async setStorybookInfo (/home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/tasks/storybookInfo.js:6:42)
  at async Task.task (/home/runner/work/_actions/chromaui/action/v1/node_modules/chromatic/bin/lib/tasks.js:13:7)
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
##[error]TypeError: Cannot destructure property `webUrl` of 'undefined' or 'null'.
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:120:33)
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
```

This is probably because the version of Storybook I am using is too new. (v6.0.0-rc.11)

That said, `npx chromatic` _does_ work for the locally. ~~i.e. chromatic v5 as opposed to v4 which this package seems to use.~~

~~Would it be possible to upgrade to chromatic v5?~~

**Comment by daniel-ac-martin** [comment]
Apologies after further investigation (reading https://github.com/chromaui/action/blob/release/v1/node_modules/chromatic/bin/lib/getStorybookInfo.js ) I think this has nothing to do with the Chromatic version. (Which is v5 unlike the `master` branch.)

It looks like the problem ultimately comes from this line: https://github.com/chromaui/action/blob/release/v1/node_modules/chromatic/bin/lib/getStorybookInfo.js#L53

Which looks like it will resolve packages from the cwd, (presumably the root of the repo).

Unfortunately, I have a monorepo and Storybook is installed into a a sub-package so it's not finding this.

I had originally thought that I could bypass this problem by pre-building my Storybook and providing this action the location.

It seems that for this to work the action would need to accept the location of the storybook installation so that it could run chromatic from that location and not the root of the repo.

**Comment by ndelangen** [comment]
@daniel-ac-martin as a work-around for now you could set a environment variable:
`CHROMATIC_STORYBOOK_VERSION=react@5.3.0`

example:
https://github.com/chromaui/action/blob/615174d5fc90df19e7dfafe842d532edd3ee7b46/.github/workflows/self-run-prod.yml#L19

**Comment by ton03** [comment]
> `CHROMATIC_STORYBOOK_VERSION=react@5.3.0`

@ndelangen I am currently using Storybook v6 as well. Does this mean that I should revert 5.3.0 (or is 5.3.18 acceptable)?

**Comment by ndelangen** [comment]
Any version of storybook is acceptable. @ton03 👍

**Comment by shelbyspeegle** [comment]
For what it's worth, I ran into this with a CD pipeline where I forgot to `yarn` before running `yarn chromatic` 😅 .

**Comment by ghengeveld** [comment]
Closing this. We're tracking monorepo support here: https://github.com/chromaui/chromatic-cli/issues/197
