### ISSUE TITLE
Expose webpack errors when building storybook

### ISSUE THREAD

**Issue by jkudish** [chromaui/action#4]
(Note: issue updated since I resolved my initial error, but would be nice to expose the error)

Hi there,

While trying to set this up in a github action on my repository, I got a webpack error. It would have been nice to expose the underlying error to make it easier to debug.

Here's the error I get: 

<img width="2280" alt="image" src="https://user-images.githubusercontent.com/260253/67880236-7cdb6880-fafb-11e9-8370-0c8e38b35859.png">

**Comment by jkudish** [comment]
Issue was related to my own webpack config (forgot to include a step that was included locally).

However, it would have been nice if the Chroma action exposed the underlying webpack error instead of just quitting. Not sure if that's easily possible

**Comment by luciano7** [comment]
any news on this? Would be helpful for my team as well.

**Comment by ndelangen** [comment]
This is on my todo list @luciano7

The action / CLI does support uploading a pre-existing folder (the output of build-storybook), so you could split the task into 2 separate steps in a github action?

**Comment by luciano7** [comment]
Oh thanks @ndelangen - I'll do that

**Comment by tmeasday** [comment]
Deployed as release 43
