### ISSUE TITLE
Support patch build argument

### ISSUE THREAD

**Issue by kylesuss** [chromaui/action#48]
The CLI has a `--patch-build` option. It doesn't seem like we support it here, but maybe we should? It does seem odd to run a patch build in CI, but someone wrote in asking about that at one point. Opening for discussion -- should we support all flags from the CLI here as well? Or do some warrant leaving out since we intend them to be run outside of CI?

**Comment by ndelangen** [comment]
In what scenario would a patch build on CI be a good idea?

**Comment by ghengeveld** [comment]
I don't think it makes sense to run a patch build from a GitHub Action.

**Comment by kylesuss** [comment]
That was my hunch as well. Something felt off, but wanted to bring it up for discussion. Sounds good. Will close this.
