### ISSUE TITLE
Action fails with TypeError

### ISSUE THREAD

**Issue by robertrbairdii** [chromaui/action#52]
I'm able to successfully upload my storybook via the CLI, but am unable to publish the built directory via the action.

I receive the following error:
```Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
    exitOnceUploaded: true
    exitZeroOnChanges: true
    storybookBuildDir: ./storybook-static
##[error]The "path" argument must be one of type string, Buffer, or URL. Received type object
##[error]TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at readFile (fs.js:295:10)
    at go$readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:7:14)
    at Object._readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/jsonfile/index.js:19:58)
    at Object._readFile [as readFile] (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:20:45)
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:66:42)
    at async Promise.all (index 0)
##[error]The "path" argument must be one of type string, Buffer, or URL. Received type object```

**Comment by ndelangen** [comment]
@robertrbairdii

Looking at the code:
```js
    const packagePath = await pkg_up_1.default(); // the user's own package.json
    const packageJson = await jsonfile_1.readFile(packagePath);
```

Is there maybe no `package.json` to be found in your repository?

**Comment by robertrbairdii** [comment]
@ndelangen I think it's related to the GitHub Actions default working directory not being respected by the chromatic action. 
See this closed issue from last week: https://github.com/chromaui/action/issues/30#issuecomment-682402605

**Comment by robertrbairdii** [comment]
I wanted to clarify my previous comment.

We currently can't have our JS codebase at the root of our repo, and must have it nested deeper within the repository. 

We're using the chromatic cli and running that as part of a pipeline to upload our storybook, but since we use GitHub actions on `pull_request` events the CLI docs explicitly state to use the action instead. Prior to running the CLI we are running the build step and have access to the static files in the pipeline. 

As it currently stands, we can't use the chromatic action itself because of the inability to specify a directory for it to run in. We have the static files from the previous step that we can upload, but the action fails either at the step that was fixed in #36 or now currently at this step in the process. My understanding of your comment in #30 was that the default run directory should be sufficient for the chromatic action to pick up the `package.json` but that doesn't appear to be the case.

**Comment by ndelangen** [comment]
@robertrbairdii I'd be happy to take a look at any repo that exhibits this problem. Do you have a reproduction repo I could investigate?

**Comment by ghengeveld** [comment]
Closing this. We're tracking monorepo support here: https://github.com/chromaui/chromatic-cli/issues/197
