### ISSUE TITLE
Recent changes have broken my CI

### ISSUE THREAD

**Issue by daniel-ac-martin** [chromaui/action#53]
It would appear that recent changes (this one?: #47) have broken my CI and my Storybook can no longer be pushed to Chromatic.

Here is an example: https://github.com/daniel-ac-martin/NotGovUK/pull/114/checks?check_run_id=1052213063

The output seems to reference the new `##[error]non-zero exit code` error referenced here: https://github.com/chromaui/action/pull/45/files#diff-8cfead41d88ad47d44509a8ab0a109adR142-R144

This is despite Chromatic having just successfully built the Storybook:

```
Building your Storybook
    → Running command: build:storybook -- --output-dir /tmp/chromatic-3385sC6Lfz8ItESj
Storybook built in 2 minutes 42 seconds
    → View build log at /home/runner/work/NotGovUK/NotGovUK/build-storybook.log
Publishing your built Storybook
    → Retrieving target location
    → Invalid Storybook build at /tmp/chromatic-3385sC6Lfz8ItESj (check the build log)

  ✖ Failed to publish your built Storybook
Invalid Storybook build at /tmp/chromatic-3385sC6Lfz8ItESj (check the build log)
```

Incidentally it says to inspect the build log, but this is tricky when Chromatic has only just created it.

Is this actually a problem with my Storybook or is it a bug in the Action?

**Comment by ghengeveld** [comment]
Hey Daniel,

You can try setting the `--output-dir` flag so it'll use a specific directory in your current working directory, rather than a random directory under `/tmp`. 

If this doesn't work out, one workaround is to run `build-storybook` yourself and pass `--storybook-build-dir` so it'll use your prebuilt Storybook.

See https://www.chromatic.com/docs/cli for details on the CLI flags.

**Comment by ghengeveld** [comment]
Closing this. If you need more help, please chat with us at https://www.chromatic.com/docs/ or open an issue in [chromatic-cli](https://github.com/chromaui/chromatic-cli/issues).
