### ISSUE TITLE
AutoAcceptChanges on multiple branches

### ISSUE THREAD

**Issue by ajkl2533** [chromaui/action#54]
Hi Chromatic team,
is it possible to pass array of branchnames into `autoAcceptChanges`? I'm using `master` branch as production and `next` breach for preparing new versions of package. But no new commit should be merged into `next` breach without code review and without passing Chromatic tests and similar situation is for the master branch so I need to somehow set the accepting for both branches.

**Comment by ghengeveld** [comment]
Yes, it supports globbing via [picomatch](https://www.npmjs.com/package/picomatch#globbing-features). That means you can do `"(master|next)"`.
