### ISSUE TITLE
Support `pull_request_target`

### ISSUE THREAD

**Issue by NicholasBoll** [chromaui/action#56]
Github Actions now support pull requests from forks: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

More info about the `pull_request_target` event type: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

However, the code explicitly prevents that type: https://github.com/chromaui/action/blob/c427f36903fb8c899e440bc90cb51822ef2959ed/src/main.ts#L25-L55

Here's an example run failure: https://github.com/Workday/canvas-kit/pull/788/checks?check_run_id=1114827451

`pull_request_target` should be a valid event.

**Note**: from our testing, adding `pull_request_target` or changing `pull_request` to `pull_request_target` in a Pull Request will result in Github Actions not running for that pull request. The event type is supposed to run code from the base branch (the branch the PR is being merged into) which gets Actions into a state where nothing triggers.

**Comment by ghengeveld** [comment]
Moving this here: https://github.com/chromaui/chromatic-cli/issues/196

Sorry I missed your PR for this. We've [moved the source code for the action](https://github.com/chromaui/chromatic-cli/tree/next/action) to the chromatic-cli repo.
