### ISSUE TITLE
Support pull_request_review

### ISSUE THREAD

**Issue by marboro92** [chromaui/action#59]
My team would like to run chromatic checks only after a review is submitted, but currently the pull_request_review event (info on this event: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_review) is not supported by chromaui. 

Would it be possible to add support for pull_request_review?

**Comment by ndelangen** [comment]
Yeah I think we can add it!

**Comment by ghengeveld** [comment]
Moved here: https://github.com/chromaui/chromatic-cli/issues/196
